### ISSUE TITLE
Tornar componentes estáticos e públicos em privados

### ISSUE THREAD

**Issue by Pliavi** [PrintFSolutions/Educake#5]
Enquanto trabalhava no projeto de LPII de Websockets usei o gerador criado, e percebi que não é necessário que os formulários contenham seus componentes como estáticos e/ou públicos, será necessário torná-los privados e adicionar seus devidos getters & setters assim que possível.

**Comment by albinofreitas** [comment]
Sim, isso segue o primeiro modelo exemplo de MVC que passei para estudarmos.
